IT-36392 / apscli, start a job with file parameter
apgsga-it/piper pull request #111
Opened 2020-10-01 10:01 UTC by apgsga-jhe

In scope of IT-36392, we need to be able to start a Job with a file as parameter. This was so far not supported by apscli. I had to refactor a bit our SSHJenkinsCommand part, because of a crazy problem with Linux pipe and Java ProcessBuilder.
The problem was similar to this one, but with "cat" command: https://stackoverflow.com/questions/3776195/using-java-processbuilder-to-execute-a-piped-command

Ideally, I would like to quickly merge this one.

2020-10-01 12:01 UTC, chhex requested changes
@apgsga-jhe  See below for comments. As stated i believe the effective Parameterization should be at as deep in the Stack as possible.... even the Command API doesn't necessarily need to know about it, the implementation sure. 
I would go for a higher level domain oriented API, which is specific about the Pipeline , which is started and as minimalistic as possible in the Parameters.

2020-10-01 13:09 UTC, apgsga-jhe commented on apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java
> +	void startJenkinsJob(String jobName, Map<JenkinsParameterType,Map> params);
@chhex : i'm stupid, we actually already have the following on JenkinsClient APIs:

`void startProdPatchPipeline(Patch patch);`

And which has been refactored already in order to pass a parameter to the corresponding Jenkins job. But so far it would be called only by DB-Status changes .... and not avaiable from the cli.

So yep, what's missing in order to start such a Job from apscli is a method you mentioned (`void startJenkinsBuildPipeline(String patchNumber);` at PatchOpService API. Then we should be able to test that from apscli (obviously with a corresponding apscli's option) without DB integration.

2020-10-02 08:43 UTC, apgsga-jhe commented
@chhex  : I made changes based on your feedback, and I'm basically now able to start a job using:
`apscli.sh -purl localhost:9010 -bp 2222`
where 2222 is my patch number.
If ok for you, I'll probably merge today or on monday.

2020-10-02 12:23 UTC, apgsga-jhe commented
@chhex : I'm merging, but won't delete the pull request, for documentation purpose, or post-review ;)

2020-10-02 12:27 UTC, merged